stages:
  - clean
  - build

clean:
  stage: clean
  script:
    - chmod +x gradlew
    - ./gradlew clean

build:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew assembleDebug
  artifacts:
    name: "digital-dukaan-${CI_BUILD_REF_NAME}-${CI_BUILD_REF}"
    paths:
      - DigitalDukaan/build/outputs/apk/*
    expire_in: 1 week