image: jangrewe/gitlab-ci-android

stages:
  - clean
  - build

clean:
  stage: clean
  script:
    - ./gradlew clean

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

build:
  stage: build
  script:
    - ./gradlew assembleLocalDebug
  artifacts:
    paths:
      - app/build/outputs/

