package com.digitaldukaan.models.response

import com.google.gson.annotations.SerializedName

data class ProfileStaticTextResponse(
    @SerializedName("page_heading") var pageHeading: String?,
    @SerializedName("text_save_change") var saveChanges: String?,
    @SerializedName("text_save") var saveText: String?,
    @SerializedName("hint_store_description_text") var storeDescriptionHint: String?,
    @SerializedName("warning_one") var mStoreLinkChangeWarningOne: String?,
    @SerializedName("warning_two") var mStoreLinkChangeWarningTwo: String?,
    @SerializedName("text_confirmation") var mStoreLinkChangeDialogHeading: String?,
    @SerializedName("edit_store_link") var editStoreLink: String?,
    @SerializedName("text_edit_store_link") var editStoreLinkText: String?,
    @SerializedName("current_link") var currentLink: String?,
    @SerializedName("text_d_dash") var dText: String?,
    @SerializedName("text_add_photo") var text_add_photo: String?,
    @SerializedName("text_dotpe_dot_in") var dotPeDotInText: String?,
    @SerializedName("store_link_condition_one") var storeLinkConditionOne: String?,
    @SerializedName("store_link_condition_two") var storeLinkConditionTwo: String?,
    @SerializedName("store_link_title") var storeLinkTitle: String?,
    @SerializedName("text_yes") var mYesText: String?,
    @SerializedName("text_update_store_name") var mBottomSheetStoreNameHeading: String?,
    @SerializedName("text_confirm") var mBottomSheetStoreButtonText: String?,
    @SerializedName("text_store_name") var text_store_name: String?,
    @SerializedName("text_confirm_desc_lose_changes") var mBottomSheetCloseConfirmationMessage: String?,
    @SerializedName("error_domain_already_exists") var mDomainAlreadyExistError: String?,
    @SerializedName("error_domain_unavailable") var mDomainUnAvailableError: String?,
    @SerializedName("heading_bank_page") var heading_bank_page: String?,
    @SerializedName("sub_heading_bank_page") var sub_heading_bank_page: String?,
    @SerializedName("hint_bank_account_holder_name") var hint_bank_account_holder_name: String?,
    @SerializedName("hint_bank_account_number") var hint_bank_account_number: String?,
    @SerializedName("hint_bank_verify_account_number") var hint_bank_verify_account_number: String?,
    @SerializedName("hint_bank_ifsc_code") var hint_bank_ifsc_code: String?,
    @SerializedName("hint_bank_registered_mobile_number") var hint_bank_registered_mobile_number: String?,
    @SerializedName("bank_save_changes") var hint_bank_save_changes: String?,
    @SerializedName("error_mandatory_field") var error_mandatory_field: String?,
    @SerializedName("error_invalid_mobile_number_field") var error_invalid_mobile_number: String?,
    @SerializedName("error_invalid_account_number") var error_invalid_account_number: String?,
    @SerializedName("error_both_account_number_verify_account_number_must_be_same") var error_both_account_number_verify_account_number_must_be_same: String?,
    @SerializedName("message_bottom_sheet_display_number_success")  var message_bottom_sheet_display_number_success: String?,
    @SerializedName("text_close")                                   var text_close: String?,
    @SerializedName("text_get_otp")                                 var text_get_otp: String?,
    @SerializedName("text_resend_otp")                              var text_resend_otp: String?,
    @SerializedName("text_no")                                      var mNoText: String?,
    @SerializedName("text_verified")                                var text_verified: String?,
    @SerializedName("text_verify")                                  var text_verify: String?,
    @SerializedName("hint_bottom_sheet_otp")                        var hint_bottom_sheet_otp: String?,
    @SerializedName("text_otp_sent_to")                             var text_otp_sent_to: String?,
    @SerializedName("text_re_enter_gst")                            var text_re_enter_gst: String?,
    @SerializedName("text_kyc_verified")                            var text_kyc_verified: String?,
    @SerializedName("bottom_sheet_gst_heading")                     var bottom_sheet_gst_heading: String?,
    @SerializedName("bottom_sheet_gst_cta_text")                    var bottom_sheet_gst_cta_text: String?,
    @SerializedName("bottom_sheet_gst_error_invalid_input")         var bottom_sheet_gst_error_invalid_input: String?,
    @SerializedName("bottom_sheet_gst_hint")                        var bottom_sheet_gst_hint: String?,
    @SerializedName("sub_heading_bottom_sheet_display_number")      var sub_heading_bottom_sheet_display_number: String?,
    @SerializedName("heading_bottom_sheet_display_number")          var heading_bottom_sheet_display_number: String?
)