package com.digitaldukaan.constants

interface AFInAppEventParameterName {

    companion object {
        const val IMAGES = "images"
        const val STORE_ID = "Store ID"
        const val SOCIAL = "Social"
        const val OFFERS = "Offers"
        const val PHONE = "phone"
        const val STATE = "STATE"
        const val PRICE = "price"
        const val AVAILABLE = "available"
        const val DESCRIPTION = "description"
        const val CATEGORY = "category"
        const val DISCOUNTED_PRICE = "discounted_price"
        const val IS_MERCHANT = "isMerchant"
        const val IS_EDIT_STORE_LINK = "iseditstorelink"
        const val IS_CATALOG = "isCatalog"
        const val IS_SETTINGS = "isSettings"
        const val IS_SETTINGS_PAGE = "isSettingsPage"
        const val REFERENCE_PHONE = "reference_phone"
        const val USER_ID = "user_id"
        const val LOCATION = "location"
        const val ORDER_ID = "orderID"
        const val LOGO_IMAGE = "logo_image"
        const val CATEGORY_NAME = "categoryName"
        const val PRODUCTS_ADDED = "productsAdded"
        const val STORE_NAME = "store_name"
        const val STORE_TYPE = "store_type"
        const val STORE_URL = "store_url"
        const val VERIFY_PHONE = "verify_phone"
        const val STORE_TYPE_DUKAAN = "Dukaan"
        const val ADDRESS = "address"
        const val AMOUNT = "Amount"
        const val SELECTION = "Selection"
        const val CHANNEL = "Channel"
        const val RESULT = "Result"
        const val PATH = "Path"
        const val IS_MARKETING_PAGE = "isMarketingPage"
        const val IS_PROFILE_PAGE = "isProfilePage"
        const val LINK = "link"
        const val GOOGLE_ADDRESS = "google_address"
        const val LATITUDE = "latitude"
        const val LONGITUDE = "longitude"
        const val ORDER_TYPE = "orderType"
        const val NUMBER_OF_ITEM = "noOfItems"
        const val DOMAIN = "domain"
        const val NAME = "name"
        const val MARKETING = "marketing"
        const val CATALOG = "catalog"
        const val REASON = "reason"
        const val VARIANTS_ADDED = "Variants_Added"
        const val SEARCH_BY = "Search by"
        const val REFERENCE_STORE_ID = "reference_store_id"
        //NOTIFICATION_CHANNEL
        const val NOTIFICATION_GROUP_ID = "DIGITAL_DUKAAN_G_ID"
        const val NOTIFICATION_GROUP_NAME = "DIGITAL_DUKAAN_G_NAME"
        const val NOTIFICATION_CHANNEL_NOTIFICATIONS = "Notifications"
        const val NOTIFICATION_CHANNEL_UPDATES = "Updates"
        const val NOTIFICATION_CHANNEL_CAMPAIGN = "Campaign"
        const val NOTIFICATION_CHANNEL_NAME = "DIGITAL_DUKAAN"
        const val NOTIFICATION_CHANNEL_DESC = "DIGITAL_DUKAAN Notifications"
    }

}