package com.digitaldukaan.constants

interface AFInAppEventParameterName {

    companion object {
        const val STEP = "Step"
        const val TYPE = "Type"
        const val KYC = "KYC"
        const val DELIVERY_CHARGE = "Delivery_charge"
        const val IMAGES = "images"
        const val STORE_ID = "Store ID"
        const val SOCIAL = "Social"
        const val OFFERS = "Offers"
        const val PHONE = "phone"
        const val STATE = "STATE"
        const val PRICE = "price"
        const val AVAILABLE = "available"
        const val DESCRIPTION = "description"
        const val CATEGORY = "category"
        const val DISCOUNTED_PRICE = "discounted_price"
        const val IS_MERCHANT = "isMerchant"
        const val IS_EDIT_STORE_LINK = "iseditstorelink"
        const val IS_CONSENT = "isConsent"
        const val IS_CATALOG = "isCatalog"
        const val IS_SETTINGS = "isSettings"
        const val IS_SETTINGS_PAGE = "isSettingsPage"
        const val REFERENCE_PHONE = "reference_phone"
        const val USER_ID = "user_id"
        const val LOCATION = "location"
        const val ORDER_ID = "orderID"
        const val TRANSACTION_ID = "txn_id"
        const val DATE_FROM = "date_from"
        const val DATE_TO = "date_to"
        const val LOGO_IMAGE = "logo_image"
        const val CATEGORY_NAME = "categoryName"
        const val PRODUCTS_ADDED = "productsAdded"
        const val STORE_NAME = "store_name"
        const val STORE_TYPE = "store_type"
        const val STORE_URL = "store_url"
        const val VERIFY_PHONE = "verify_phone"
        const val STORE_TYPE_DUKAAN = "Dukaan"
        const val ADDRESS = "address"
        const val AMOUNT = "Amount"
        const val SELECTION = "Selection"
        const val CHANNEL = "Channel"
        const val BING_TEXT = "Bing_Text"
        const val RESULT = "Result"
        const val PATH = "Path"
        const val NEW_RELEASES = "new_releases"
        const val MORE_CONTROLS = "more_controls"
        const val SETTINGS_PAGE = "Settings Page"
        const val ACTIVATION_SCREEN = "activation_screen"
        const val LOCK_BUTTON_CLICKED = "lock_button_click"
        const val IS_MARKETING_PAGE = "isMarketingPage"
        const val IS_ORDER_PAGE = "isOrderPage"
        const val IS_SETTLEMENT_PAGE = "isSettlementPage"
        const val IS_MARKETING = "isMarketing"
        const val IS_PROFILE_PAGE = "isProfilePage"
        const val LINK = "link"
        const val GOOGLE_ADDRESS = "google_address"
        const val PAYMENT_ORDERS = "payment_orders"
        const val SETTLEMENTS = "settlements"
        const val ORDER_DETAILS = "order_details"
        const val LATITUDE = "latitude"
        const val LONGITUDE = "longitude"
        const val ORDER_TYPE = "orderType"
        const val NUMBER_OF_ITEM = "noOfItems"
        const val DOMAIN = "domain"
        const val NAME = "name"
        const val MARKETING = "marketing"
        const val CATALOG = "catalog"
        const val REASON = "reason"
        const val PREPAID = "Prepaid"
        const val BOTH = "Both"
        const val TRUE = "True"
        const val POSTPAID = "Pay_on_delivery"
        const val VARIANTS_ADDED = "Variants_Added"
        const val SEARCH_BY = "Search by"
        const val SELECT = "SELECT"
        const val REFERENCE_STORE_ID = "reference_store_id"
        //NOTIFICATION_CHANNEL
        const val NOTIFICATION_GROUP_ID = "DIGITAL_DUKAAN_G_ID"
        const val NOTIFICATION_GROUP_NAME = "DIGITAL_DUKAAN_G_NAME"
        const val NOTIFICATION_CHANNEL_NOTIFICATIONS = "Notifications"
        const val NOTIFICATION_CHANNEL_UPDATES = "Updates"
        const val NOTIFICATION_CHANNEL_CAMPAIGN = "Campaign"
        const val NOTIFICATION_CHANNEL_NAME = "DIGITAL_DUKAAN"
        const val NOTIFICATION_CHANNEL_DESC = "DIGITAL_DUKAAN Notifications"
    }

}